version: '3.9'
services:
  web_api:
    image: web_api
    build: ./AGSR.Patients
    container_name: web_api_application
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<YOUR PASSWORD>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: AGSR_sql_server2022
    ports:
      - "1433:1433"
    environment:
        - ACCEPT_EULA=y
        - SA_PASSWORD=<SA_PASSWORD>